DARMA-tasking/LB-analysis-framework

- src/Applications/NodeGossiper.py
- src/Execution/lbsCriterion.py
- src/Execution/lbsRelaxedLocalizingCriterion.py
- src/Execution/lbsRuntime.py
- src/Execution/lbsStrictLocalizingCriterion.py
- src/IO/lbsStatistics.py
This PR also improves the overall usage of quantitative criteria (by favoring acceptance of transfer vs rejection in cases of draws).
Reference case:
`./NodeGossiper.py -i 2 -x 4 -y 4 -z 1 -p 4 -o 1024 -k 2 -f 2 -t uniform,1.0,1.0 -w lognormal,0.5,1.0 -d 2`
with the **strictly** localizing criterion (`-c 2`) one obtains:
```
[Statistics] Descriptive statistics of final processor loads:
cardinality: 16  sum: 1024  imbalance: 2.17188
minimum: 14  mean: 64  maximum: 203
standard deviation: 60.024  variance: 3602.88
skewness: 1.34027  kurtosis excess: 0.154602
[Statistics] Descriptive statistics of final link weights:
cardinality: 53  sum: 2188.62  imbalance: 6.21218
minimum: 1.19894  mean: 41.2947  maximum: 297.825
standard deviation: 80.3113  variance: 6449.9
skewness: 2.47807  kurtosis …
```
> Close #20: rewrite lost strict localizer

- src/Applications/AnimationViewer.py
- src/Applications/NodeGossiper.py
- src/Applications/PNGViewer.py
- src/Applications/ParaviewViewer.py
- src/Applications/ParaviewViewerBase.py
Opening new PR since issue description changed.  
Visualization artifacts are now generated when specified in command line with `-e` argument, followed by the string to be used as prefix of viz file naming. Please note that it is possible to specify an empty string in which case, the name of the generated ExodusII file is used by default for viz files too.
> 27 vistool import optional

- src/Applications/MoveCountsViewer.py
- src/Applications/NodeGossiper.py
- src/IO/lbsLoadReaderVT.py
- src/Model/lbsPhase.py
- added option `-j` for data reading file suffix
- defaulf file suffix is `.vom`
- file suffix needs to be given after `-j` E.g. `-j out` => then `*.out` file will be read instead of default `*.vom`
Closes #70
> #70: Make extension of VOM files a command line option

- src/Applications/rank-object-enumerator.py
Fixes #141 
It is working as expected, i.e., for "pure" load-balancing:
```
[pppebay@localhost]~/Documents/Git/LB-analysis-framework/src/Applications$ python rank-object-enumerator.py
alpha: 1.0
beta: 0.0
gamma: 0.0
Initial works: {0: 2.5, 1: 4.0, 2: 1.5}
maximum work: 4 average work: 2.667
Number of generated arrangements: 262144
minimax work: 2 for 840 arrangements
Example optimal arrangement: (0, 0, 0, 1, 1, 2, 1, 3, 3)
maximum work: 2 average work: 2
```
or for "pure" communication volume minimization:
```
[pppebay@localhost]~/Documents/Git/LB-analysis-framework/src/Applications$ python rank-object-enumerator.py
alpha: 0.0
beta: 1.0
gamma: 0.0
Initial works: {0: 3.5, 1: 4.5, 2: 2.5}
maximum work: 4.5 average work: 3.5
Number of generated arrangements: 262144
minimax work: 0 for 16 …
```
> #141 create brute force optimizer for reference base cases

- src/Applications/rank_object_enumerator.py
- added logger
- added reading configuration from conf file
- added get_objects function which reads from log files
- made functions independent from variables from outer scope
- changed print statements to logger statements
- take output directory from configuration
close #157
> #157: Make the rank-object-enumerator app use the conf.yaml file

- src/Applications/LBAF.py
- src/Applications/conf.yaml
- added `output_file_stem` key to the config file
- added support in LBAF for output file stem
close #171
> #171: Have LBAF use a (new) output_file_stem variable for output files

- scripts/test_lbaf.py
- src/Applications/LBAF.py
- src/Applications/conf.yaml
- added `config_file` as input parameter for `internalParameters` class
close #180 
@ppebay CI test is failing. I didn't make any changes which could make that happend. Config file is under `scripts/test_config.conf.yaml` please take a look. I also added print statement in test. It prints now found imbalance:
```shell
[LBAF] Process complete ###
@@@@@ FOUND IMBALANCE: 0.75 @@@@@
===> TEST FAILED!
```
> 180 Make name of configuation file a mandatory parameter of LBAF

- scripts/test_config/conf.yaml
- src/Applications/rank_object_enumerator.py
- src/Execution/lbsRuntime.py
- src/IO/lbsVTDataReader.py
- src/Model/lbsObject.py
- tests/test_lbs_vt_statistics_reader.py
- removed __hash__ and __eq__ from lbsObject
- fixed formatting and typos in lbsRuntime and lbsDataReader
- reorganized rank_object_enumerator, so it works in both data reader and simulation from samplers
- fixed failing tests because of the changes
- fixed location of the data for testing config
Closes #204
> #204: make rank object enumerator usable in lbaf

- src/lbaf/Applications/LBAF_app.py
- src/lbaf/Applications/conf.yaml
- src/lbaf/IO/configurationValidator.py
- src/lbaf/IO/schemaValidator.py
- removed traceback when use `schema` library 
- added show_traceback to configuration file (default False)
- added `show_traceback` to configuration validator as optional
- added traceback setup to the LBAF init
Closes #249
> #249: Gracefully exit from configuration validator

- src/lbaf/Applications/step.yaml
- src/lbaf/IO/lbsMeshWriter.py
- src/lbaf/Model/lbsRank.py
This had to do finally more with using consistent ordering across phases: sentinel objects first, then migratable ones -- and always ordering them inside their local "blocks".
> #260: implemented issue (but it has nothing to do with jitter finally)

- src/lbaf/Applications/LBAF_app.py
- src/lbaf/Applications/conf.yaml
- src/lbaf/IO/configurationValidator.py
- src/lbaf/IO/schemaValidator.py
- src/lbaf/Model/lbsPhase.py
- removed `show_traceback` from conf.yaml
- removed `show_traceback` and exception_handler from configurationValidator.py
- removed `show_traceback` from LBAF
- added `import sys` as it was missing in lbsPhase.py
- changed method responsible for handling exceptions in schemaValidator.py
closes #272
> #272: Remove show_traceback option from configuration

- src/lbaf/Applications/LBAF_app.py
- src/lbaf/Applications/conf.yaml
- src/lbaf/IO/configurationValidator.py
- tests/data/config/conf_correct_phase_ids_str_001.yml
- tests/data/config/conf_wrong_phase_ids_str_001.yml
- tests/test_configuration_validator.py
- added info in conf.yaml
- added tests of enhanced configuration option with two sample configurations
- modified parsing data parameters in LBAF_app
- modified configurationValidator.py, so it accepts str and validates it with Regex
closes #277
> #277: Accept range in phase indices in lbaf config

- src/lbaf/IO/lbsMeshBasedVisualizer.py
fixes #287 
This is only a short-term fix, allowing for the visualization of data sets with variable number of objects across phases. It will only make sense if the jitter value is set to 0 globally.
> #287: allow for a default 0-value of the jitter

- src/lbaf/IO/lbsVTDataWriter.py
- tests/test_vt_data_extractor.py
- change time with load in VTDataWriter
Output from our `synthetic data`:
```Python3
{"phases":[{"tasks":[{"load":0.5,"resource":"cpu","object":7},{"load":1.0,"resource":"cpu","object":0},{"load":0.5,"resource":"cpu","object":4}],"id":0}]}
{"phases":[{"tasks":[{"load":2.0,"resource":"cpu","object":5}],"id":1}]}
{"phases":[{"tasks":[{"load":0.5,"resource":"cpu","object":2},{"load":1.5,"resource":"cpu","object":8}],"id":2}]}
{"phases":[{"tasks":[{"load":0.5,"resource":"cpu","object":3},{"load":1.0,"resource":"cpu","object":6},{"load":0.5,"resource":"cpu","object":1}],"id":3}]}
```
closes #281
> #281: "time" key must be replaced with "load" for objects in JSON files

- src/lbaf/Execution/lbsBruteForceAlgorithm.py
- src/lbaf/Execution/lbsRecursiveTransferStrategy.py
- src/lbaf/Execution/lbsTransferStrategyBase.py
- tox.ini
> #392: Make pylint errors cause a CI failure

- src/lbaf/IO/lbsVTDataReader.py
- tests/unit/data/synthetic_lb_data/README.md
- tests/unit/test_lbs_vt_data_reader.py
Fixes #403 
The `n_ranks` value detection is now using regex against data file names when it does not exist in meta data.
n_ranks is now using `max(rank_id) + 1` where `rank_id`'s are extracted from the file name (because file are named like : `{file_prefix}.{rank_id}.{file_suffix}`
> #403: fix n_ranks using data files better detection with regex

- config/global.yaml
- src/lbaf/Applications/LBAF_app.py
- tests/unit/test_lbaf_app.py
Fixes #352 
- Adds support of global configuration file if present at <project_path>/config/global.yaml or <cwd>/global.yaml 
- Add basic global.yaml file with output_dir default value of "../output". 
I think it will be important later to define what goes in global.yaml and what should be removed for some configurations files on the repo (like the "output_dir" key)
> #352: Create baseline/global YAML configuration file

- src/lbaf/Applications/LBAF_app.py
- src/lbaf/Execution/lbsAlgorithmBase.py
- src/lbaf/Execution/lbsCentralizedPrefixOptimizerAlgorithm.py
- src/lbaf/IO/lbsConfigurationValidator.py
- src/lbaf/Model/lbsRank.py
Fixes #324 
Still very much a draft. Need to figure out better way for comparison operator.
> #324 implement centralized memory constraint

- src/lbaf/Execution/lbsCentralizedPrefixOptimizerAlgorithm.py
- tests/unit/test_vt_data_extractor.py
Fixes #418 
The test related to the vt_data_extractor was in fact failing due to a missing assertion possible value.
Now it works correctly.
Fix also some pylint warnings
> #418: Failure of test_vt_data_extractor_014 in CI

- .gitignore
- README.md
- requirements.txt
- src/lbaf/Applications/LBAF_app.py
- src/lbaf/Applications/MoveCountsViewer.py
- src/lbaf/Utils/lbsCsv2JsonDataConverter.py
- src/lbaf/Utils/lbsDataStatFilesUpdater.py
- src/lbaf/Utils/lbsJSONDataFilesValidatorLoader.py
- src/lbaf/Utils/lbsVTDataExtractor.py
- src/lbaf/__init__.py
- src/lbaf/__main__.py
- tests/acceptance/test_acceptance.py
- tests/acceptance/test_stepper.py
- tests/test_lbs_inform_and_transfer_algorithm.py
- tests/unit/test_JSON_data_files_validator.py
- tests/unit/test_configuration_validator.py
- tests/unit/test_lbaf_app.py
- tests/unit/test_lbs_message.py
- tests/unit/test_lbs_object.py
- tests/unit/test_lbs_object_communicator.py
- tests/unit/test_lbs_phase.py
- tests/unit/test_lbs_rank.py
- tests/unit/test_lbs_statistics.py
- tests/unit/test_lbs_vt_data_reader.py
- tests/unit/test_lbs_work_model_base.py
- tests/unit/test_schema_validator.py
- tests/unit/test_vt_data_extractor.py
- tests/unit/test_vt_writer.py
Fixes #376 
This PR 
- Restore the way to run LBAF not as a package. When package is not installed then the lbaf module will be resolved relative to the current project directory automatically.
- For users who want to run development mode using lbaf as a package they will have to run `pip install -e .` since it has been removed from requirements.txt
- README.md file has also been re-worked to explain how to use lbaf as a package & adds information about using virtual environments
- Tests are again run against the lbaf source directory (no more the package installation because it may not be installed as a package now)
> #376: Enable multiple versions of lbaf to run in the same python environment

- src/lbaf/Applications/LBAF_app.py
- src/lbaf/IO/lbsConfigurationValidator.py
- src/lbaf/IO/lbsVTDataReader.py
Fixes #426 
This PR includes:
- Fix `n_ranks `value detection by using only from the data file names (no more use `num_nodes` from data files as `n_ranks`)
- Add new optional `expected_ranks` configuration key (int value) to `from_data` configuration node. If it is set and `n_ranks` is different from `expected_ranks` a warning message is displayed to the user.
> #426: Number of input files detected incorrectly

- src/lbaf/Execution/lbsClusteringTransferStrategy.py
- src/lbaf/IO/lbsVTDataReader.py
Fixes #437 
**N.B.:** the error was beyond the `PhaseStepper` only; it was due to an incorrect variable been reported when an error condition was met in the vt Reader.
> #437: clarify phase stepper error report

- src/lbaf/Applications/LBAF_app.py
> #453: Fix FileNotFoundError in lbaf v1.0.0 package

- src/lbaf/Execution/lbsInformAndTransferAlgorithm.py
- src/lbaf/IO/lbsConfigurationValidator.py
- tests/unit/config/conf_correct_clustering_target_imb.yml
- tests/unit/test_configuration_validator.py
> #431: Add a target imbalance threshold to yaml

- src/lbaf/Execution/lbsAlgorithmBase.py
- src/lbaf/Utils/lbsJSONDataFilesValidatorLoader.py
- src/lbaf/__init__.py
Fixes #475
The issue was the use of absolute file paths; since the package directory structure is slightly different from the source code (no `src` dir), we should use relative paths whenever possible.
I also changed `overwrite` to False when lbaf is installed as a package, as discussed in the meeting.
> #475: Investigate failing PyPi package (v1.0.1)

- config/challenging-toy-hundreds-tasks.yaml
- src/lbaf/Execution/lbsAlgorithmBase.py
- src/lbaf/Execution/lbsClusteringTransferStrategy.py
- src/lbaf/Execution/lbsTransferStrategyBase.py
- src/lbaf/IO/lbsConfigurationValidator.py
- tests/unit/config/conf_wrong_max_subclusters_mag.yml
- tests/unit/config/conf_wrong_max_subclusters_type.yml
- tests/unit/test_configuration_validator.py
- tests/unit/test_lbs_inform_and_transfer_algorithm.py
- tests/unit/test_lbs_work_model_base.py
> #484: Keep tempered algorithm in sync with implementation in vt

- config/test-vt-tv.yaml
- src/lbaf/Applications/LBAF_app.py
- src/lbaf/IO/lbsVTDataReader.py
- src/lbaf/IO/lbsVTDataWriter.py
- src/lbaf/Model/lbsObject.py
- src/lbaf/Model/lbsObjectCommunicator.py
> #422: Stream data to vt-tv for rendering

- src/lbaf/Applications/LBAF_app.py
- tests/acceptance/test_permutations.py
Fixes #547 
Cases tested in this PR:
- load-only: `W_max=2.0`
- off-node-communication-only: `W_max=0.0`
---
This PR makes the same changes as #541 to write out `w_max.txt` when we run LBAF.
I also altered the `LBAFApplication.run()` function so that we can call it directly from tests with a configuration dict. This allows us to:
1. avoid using `subprocess.run()` to call LBAF
2. avoid having to create separate configuration files for each test case
Now we can run LBAF in tests with:
```python
lbaf = LBAFApplication()
lbaf.run(cfg=config, cfg_dir=acceptance_dir)
```
> #547: Add tests for new PrescribedPermutation algorithm

- .github/workflows/deploy_docs.yml
- docs/docs_config.py
Fixes #551 
The problem stems from [this commit](https://github.com/mosra/m.css/commit/33265c8b79c9b2a2c460830394ad5cf9a27ead32) to `m.css`. The change is described below (copied from the linked commit's message), where the "additional check" mentioned was throwing errors for us:
```
The use case is explicitly including a module that otherwise doesn't get
transitively imported from the parents. They were treated as a standalone
root module until now, causing quite a mess. Now they aren't, but there's
an additional check requiring the user to explicitly supply also all
parents.
```
Also reworks the doc deployment pipeline so that the docs are built on every PR, but only deployed on pushes to `develop` or `main`. This way we'll catch errors in the pipeline before merging PRs.
> #551: Fix INPUT_MODULE ordering

- config/conf.yaml
- config/synthetic-blocks.yaml
- src/lbaf/Applications/LBAF_app.py
- src/lbaf/Execution/lbsAlgorithmBase.py
- src/lbaf/Execution/lbsBruteForceAlgorithm.py
- src/lbaf/Execution/lbsCentralizedPrefixOptimizerAlgorithm.py
- src/lbaf/Execution/lbsInformAndTransferAlgorithm.py
- src/lbaf/Execution/lbsPhaseStepperAlgorithm.py
- src/lbaf/Execution/lbsPrescribedPermutationAlgorithm.py
- src/lbaf/Execution/lbsRuntime.py
- src/lbaf/IO/lbsConfigurationValidator.py
- src/lbaf/IO/lbsStatistics.py
- tests/unit/Execution/test_lbs_brute_force_algorithm.py
- tests/unit/Execution/test_lbs_centralized_prefix_optimizer_algorithm.py
- tests/unit/Execution/test_lbs_inform_and_transfer_algorithm.py
- tests/unit/Execution/test_lbs_runtime.py
Related to #566 
Does not resolve it but is a checkpoint towards #566 in order to merge with PR #567 and avoid conflicts
> #566: refactoring prior to supporting lb iterations

- src/lbaf/Applications/LBAF_app.py
- src/lbaf/Execution/lbsAlgorithmBase.py
- src/lbaf/Model/lbsObject.py
- src/lbaf/Model/lbsQOIDecorator.py
- src/lbaf/Model/lbsRank.py
> #567: QOIs: refactor to use a decorator

- src/lbaf/IO/lbsVTDataWriter.py
- src/lbaf/Model/lbsPhase.py
- src/lbaf/Model/lbsRank.py
Fixes #571 
**N.B.:** This requires a slightly different handling of shared block deletion.
The only place where this change actually has an impact currently is in the vt data reader, specifically lines 191 and 211
> #571: Resolve problem of shallow copying of objects that invalidates lookup table

- src/lbaf/Applications/LBAF_app.py
- src/lbaf/Execution/lbsAlgorithmBase.py
- src/lbaf/Execution/lbsInformAndTransferAlgorithm.py
- src/lbaf/IO/lbsVTDataReader.py
- src/lbaf/IO/lbsVTDataWriter.py
- src/lbaf/Model/lbsBlock.py
- src/lbaf/Model/lbsObject.py
- src/lbaf/Model/lbsQOIDecorator.py
- src/lbaf/Model/lbsRank.py
- tests/unit/Model/test_lbs_block.py
Fixes #562
Linked to:
- https://github.com/DARMA-tasking/vt-tv/pull/129
- https://github.com/DARMA-tasking/vt/pull/2376
> #562: output: add output to JSON for vt-tv for derived stats

- src/lbaf/IO/lbsVTDataReader.py
Fixes #573 
**N.B.:** upon verification no bug was actually present and the incorrect phase detection was actually done. This PR is use to nonetheless make stylistic changes to the vt data reader as some Pylint defects had to be addressed anyway.
> #573: verified that no bug is actually present but made stylistic changes

- config/synthetic-blocks.yaml
- src/lbaf/Execution/lbsClusteringTransferStrategy.py
- src/lbaf/IO/lbsConfigurationValidator.py
- tests/unit/IO/test_configuration_validator.py
> #584: Add option to run cluster transfer based algorithms without subclustering

- config/synthetic-blocks.yaml
- config/user-defined-memory-toy-problem.yaml
- src/lbaf/Applications/LBAF_app.py
- src/lbaf/Execution/lbsAlgorithmBase.py
- src/lbaf/Execution/lbsCentralizedPrefixOptimizerAlgorithm.py
- src/lbaf/IO/lbsConfigurationValidator.py
- src/lbaf/IO/lbsVTDataReader.py
- src/lbaf/Model/lbsAffineCombinationWorkModel.py
- src/lbaf/Model/lbsBlock.py
- src/lbaf/Model/lbsNode.py
- src/lbaf/Model/lbsObject.py
- src/lbaf/Model/lbsPhase.py
- src/lbaf/Model/lbsRank.py
- tests/acceptance/test_synthetic_blocks.py
- tests/unit/Execution/test_lbs_clustering_transfer_strategy.py
- tests/unit/Execution/test_lbs_recursive_transfer_strategy.py
- tests/unit/Model/test_lbs_block.py
- tests/unit/Model/test_lbs_node.py
- tests/unit/Model/test_lbs_object.py
- tests/unit/Model/test_lbs_rank.py
> #558: Restructured PR to add node level memory constraint post recent changes

- src/lbaf/Utils/lbsJSONTaskLister.py
> #587: Modify JSON task lister to make it usable even when LBAF is not installed

- config/conf.yaml
- config/synthetic-blocks.yaml
- docs/pages/configuration.rst
- docs/pages/testing.rst
- src/lbaf/Applications/LBAF_app.py
- src/lbaf/Execution/lbsAlgorithmBase.py
- src/lbaf/Execution/lbsBruteForceAlgorithm.py
- src/lbaf/Execution/lbsCentralizedPrefixOptimizerAlgorithm.py
- src/lbaf/Execution/lbsCriterionBase.py
- src/lbaf/Execution/lbsInformAndTransferAlgorithm.py
- src/lbaf/Execution/lbsPhaseStepperAlgorithm.py
- src/lbaf/Execution/lbsPrescribedPermutationAlgorithm.py
- src/lbaf/Execution/lbsRuntime.py
- src/lbaf/Execution/lbsStrictLocalizingCriterion.py
- src/lbaf/IO/lbsConfigurationValidator.py
- tests/acceptance/test_synthetic_blocks.py
- tests/unit/Execution/test_lbs_centralized_prefix_optimizer_algorithm.py
- tests/unit/Execution/test_lbs_runtime.py
- tests/unit/config/conf_correct_003.yml
- tests/unit/config/conf_correct_brute_force.yml
Resolve #596 #550 
**N.B. for reviewers:** upon closer inspection, it does not make much sense to update this method which in fact is now seldom (if ever) used, as the MILP advantageously replaces it by allowing to compute optima in a much more scalable way: the brute force option calling the max arrangement computation does not work past a few ranks and objects due to combinatorial explosion. The code has thus been refactored to entirely do away with this baseline comparison approach which _de facto_ was no longer used -- and causes substantial maintenance challenges.
As a side note I suggest we make MILP callable directly from LBAF (which we discussed in the past @lifflander and for which some very preliminary work had been done but that has not been touched in quite a while now).
> #596: Replace hard-coded 1.0 with actual local alpha values for the computation of max arrangement work statistics

- config/challenging-toy-hundreds-tasks.yaml
- src/lbaf/Execution/lbsClusteringTransferStrategy.py
- src/lbaf/Execution/lbsInformAndTransferAlgorithm.py
- src/lbaf/Model/lbsRank.py
> #605: include all changes made during information stage study

- config/challenging-toy-fewer-tasks.yaml
- config/challenging-toy-hundreds-tasks.yaml
- config/conf.yaml
- config/synthetic-blocks.yaml
- docs/pages/configuration.rst
- docs/pages/testing.rst
- src/lbaf/Applications/LBAF_app.py
- src/lbaf/Execution/lbsAlgorithmBase.py
- src/lbaf/Execution/lbsBruteForceAlgorithm.py
- src/lbaf/Execution/lbsInformAndTransferAlgorithm.py
- src/lbaf/Execution/lbsTransferStrategyBase.py
- src/lbaf/IO/lbsConfigurationValidator.py
- src/lbaf/IO/lbsStatistics.py
- src/lbaf/Model/lbsAffineCombinationWorkModel.py
- src/lbaf/Model/lbsPhase.py
- src/lbaf/Model/lbsRank.py
> #607: Add homing (delta) term

- config/challenging-toy-fewer-tasks.yaml
- config/challenging-toy-hundreds-tasks.yaml
- config/conf.yaml
- config/synthetic-blocks.yaml
- docs/pages/configuration.rst
- docs/pages/testing.rst
- src/lbaf/Applications/LBAF_app.py
- src/lbaf/Execution/lbsAlgorithmBase.py
- src/lbaf/Execution/lbsBruteForceAlgorithm.py
- src/lbaf/Execution/lbsClusteringTransferStrategy.py
- src/lbaf/Execution/lbsInformAndTransferAlgorithm.py
- src/lbaf/Execution/lbsPhaseSpecification.py
- src/lbaf/Execution/lbsTransferStrategyBase.py
- src/lbaf/IO/lbsConfigurationValidator.py
- src/lbaf/IO/lbsStatistics.py
- src/lbaf/Model/lbsAffineCombinationWorkModel.py
- src/lbaf/Model/lbsPhase.py
- src/lbaf/Model/lbsRank.py
- src/lbaf/Utils/lbsJSONDataFilesMaker.py
- src/lbaf/Utils/lbsJSONSpecFileMaker.py
> #609: add latest changes to master
