src/Model/lbsProcessor.py
=> 26 do not self inform during gossiping phase

src/Applications/AnimationViewer.py, src/Applications/MoveCountsViewer.py, src/Applications/NodeGossiper.py, src/Applications/PNGViewer.py, src/Applications/ParaviewViewer.py, src/Applications/ParaviewViewerBase.py, src/Execution/lbsCriterionBase.py, src/Execution/lbsRuntime.py, src/IO/lbsGridStreamer.py, src/IO/lbsLoadReaderVT.py, src/IO/lbsLoadWriterVT.py, src/IO/lbsStatistics.py, src/IO/lbsWriterExodusII.py, src/Model/lbsProcessor.py
Should cover all missing preambles. Needs to me pulled soon to make sure new commits include this new way of printing log, and avoid behavior gap.
=> 41 missing color preambles

src/Applications/NodeGossiper.py
- added project path to system path automatically
=> #68: Fix import bug

src/Execution/lbsRuntime.py, src/IO/lbsStatistics.py, src/Model/lbsProcessor.py
The CMF problem is now fixed and it seems that the performance of LBAF was even slightly improved. If approved that change should go into GossipLB
=> 72 fix incorrect empirical cmf computation under new criterion

requirements.txt, scripts/test_lbaf.py, src/Applications/LBAF.py, src/Applications/conf.yaml
- change name NodeGossiper to LBAF
- added conf.yaml to Applications directory
- added PyYAML to requirements.txt
- configuration docs inside conf.yaml file
closes #46
=> #46: Add a configuration file

scripts/multi_reg.py, src/Applications/NodeGossiper.py, src/Execution/lbsRuntime.py, src/Model/lbsProcessor.py
Please note that for now, data input files are supposed to be co-located with the script and have names matching `in.*.dat`
=> 84 multiple correlation to determine lb predictors

src/Applications/NodeGossiper.py, src/Execution/lbsRuntime.py, src/Model/lbsProcessor.py
Also will include some additional improvements related to now-closed #72
=> Draft: #76: add capability to study order of object selection in transfer stage

src/Applications/LBAF.py, src/Applications/conf.yaml, src/IO/lbsLoadReaderVT.py, src/Model/lbsPhase.py
- changed config file
- enchances populated from samplers option
- added communication reading
resolve #87
=> #87: Ensure proper mirroring of edge storage

src/Execution/lbsRelaxedLocalizingCriterion.py, src/Execution/lbsStrictLocalizingCriterion.py
- changed error message and termination
resolve #104
=> Runtime error when trying to use strict localizing criterion

src/IO/lbsLoadWriterVT.py
- removed unecessary comment
- shorten too long line
resolve #101
=> Fix now outdated CSV comments/online doc

src/Execution/lbsCriterionBase.py, src/Execution/lbsGrapevineCriterion.py, src/Execution/lbsModifiedGrapevineCriterion.py, src/Execution/lbsRelaxedLocalizingCriterion.py, src/Execution/lbsStrictLocalizingCriterion.py, src/IO/lbsLoadReaderVT.py, src/IO/lbsLoadWriterVT.py, src/IO/lbsWriterExodusII.py, src/Model/lbsPhase.py, src/Model/lbsRank.py
- renamed Processor into Rank
resolve #98
=> #98: Rename Processor into Rank

src/Applications/conf.yaml, src/Execution/lbsLowerTotalWorkCriterion.py, src/Model/lbsPhase.py
=> #110 debug and improve total work criterion

src/Applications/LBAF.py, src/Applications/conf.yaml, src/Execution/lbsCriterionBase.py, src/Execution/lbsLowerTotalWorkCriterion.py, src/Execution/lbsRuntime.py
=> #114: refactored parameters/criterion construction as needed

src/Applications/LBAF.py
- removed cmd line args
resolve #117
=> #117: Deprecate command line support entirely

src/Applications/conf.yaml, src/Execution/lbsLowerTotalWorkCriterion.py, src/Execution/lbsRuntime.py, src/Execution/lbsTemperedLoadCriterion.py, src/Model/lbsRank.py
This needs to be thoroughly reviewed to ensure the modified algorithm is working properly
=> Removal of average load dependency

scripts/test_lbaf.py, src/Applications/LBAF.py, src/Applications/conf.yaml, src/Execution/lbsRuntime.py, src/Model/lbsRank.py
=> modify optimization loop to not be solely load-based

src/Applications/LBAF.py, src/Applications/ParaviewViewerBase.py, src/Applications/conf.yaml, src/Execution/lbsLowerTotalWorkCriterion.py, src/Execution/lbsRelaxedLocalizingCriterion.py, src/Execution/lbsRuntime.py, src/IO/lbsLoadReaderVT.py, src/IO/lbsWriterExodusII.py, src/Model/lbsObjectCommunicator.py, src/Model/lbsPhase.py
=> #126: replaced weight with volume for communication nomenclature

src/Applications/LBAF.py, src/Applications/conf.yaml, src/Execution/lbsCriterionBase.py, src/Execution/lbsLowerTotalWorkCriterion.py, src/Execution/lbsRelaxedLocalizingCriterion.py, src/Execution/lbsRuntime.py, src/Execution/lbsStrictLocalizingCriterion.py, src/Execution/lbsTemperedLoadCriterion.py, src/IO/lbsWriterExodusII.py, src/Model/lbsPhase.py, src/Model/lbsRank.py
=> modify ExodusII output to support bidirectional edges

src/Applications/LBAF.py, src/Execution/lbsRuntime.py, src/IO/lbsLoadReaderVT.py, src/IO/lbsStatistics.py, src/Model/lbsLoadOnlyWorkModel.py, src/Model/lbsPhase.py, src/Model/lbsRank.py, src/Model/lbsWorkModelBase.py
=> #130 Modify load to become more generic work and make it abstract

src/Applications/LBAF.py, src/Applications/conf.yaml, src/Execution/lbsRuntime.py, src/IO/lbsGridStreamer.py, src/IO/lbsLoadWriterVT.py, src/IO/lbsWriterExodusII.py
fixes #133 
Also improves `vtLoadWriter`
=> #133: store work and work statistics in ExodusII 

src/Applications/LBAF.py, src/Applications/conf.yaml, src/Execution/lbsCriterionBase.py, src/Execution/lbsRuntime.py, src/Execution/lbsTemperedWorkCriterion.py, src/IO/lbsLoadReaderVT.py, src/IO/lbsLoadWriterVT.py, src/IO/lbsWriterExodusII.py, src/Model/lbsAffineCombinationWorkModel.py, src/Model/lbsObject.py, src/Model/lbsPhase.py, src/Model/lbsRank.py, src/Model/lbsWorkModelBase.py
=> #134: implement concrete work based on combination of load and communication

src/Utils/logger.ini
- added ppp formatter
- changed the default level from debug to info
=> #143: Modify output of logging method

src/Applications/LBAF.py, src/Utils/__init__.py, src/Utils/logger.ini
- added function which passing config value of `logging_level` to `logger.ini`
resolve #145
=> #145: Fix logging levels of logger

src/Applications/conf.yaml, src/Execution/lbsRuntime.py, src/IO/lbsStatistics.py, src/Model/lbsRank.py
=> #122: implement work-based CMF method

lbaf.Dockerfile, scripts/test_config/conf.yaml, scripts/test_lbaf.py, src/Applications/LBAF.py, src/IO/lbsStatistics.py
- setup configuration for the test
- changed dockerfile
- changed saving imbalance in LBAF
close #125
=> #125: Setup new testing for LBAF

src/Applications/conf.yaml, src/Utils/logger.py
- added `terminal_background` option in conf.yaml
- fixed added more than one handler
close #154
=> #154: Logger printing white characters in the message body

src/Applications/rank-object-enumerator.py
- added reading from a config file
- assigned values from a config file instead of hardcoded values
- added function annotations
- fixed possible typo
close #157
=> #157: Make the rank-object-enumerator app use the conf.yaml file

src/Applications/LBAF.py, src/Applications/conf.yaml, src/Applications/rank-object-enumerator.py, src/Execution/lbsRuntime.py, src/IO/lbsLoadWriterVT.py
=> #160 #161 make recursiveness of transfer function configurable and make rank objecte numerator enumerate all optimal cases to a file

requirements.txt, src/Applications/MoveCountsViewer.py
- improved MoveCountsViewer.py
- updated requirements.txt to the latest versions
- made MoveCountsViewer.py to work as well without command line arguments
close #166
=> #166: vtk does not appear to provide vtk graph layout

src/Execution/lbsRuntime.py
- added logger error message regarding incorrect order strategy and exits when error
close #177
=> #177: Gracefully handle incorrect order strategy names

src/Applications/LBAF.py, src/Applications/conf.yaml, src/Execution/lbsCriterionBase.py, src/Execution/lbsRelaxedLocalizingCriterion.py, src/Execution/lbsRuntime.py, src/Execution/lbsStrictLocalizingCriterion.py, src/Execution/lbsTemperedCriterion.py, src/IO/lbsLoadReaderVT.py, src/IO/lbsStatistics.py, src/Model/lbsPhase.py, src/Model/lbsWorkModelBase.py
Fixes #121 (cf. same issue for discussion)
=> #121: modify ordering strategies to remove use of load average

src/Applications/LBAF.py, src/Applications/conf.yaml, src/Applications/rank_object_enumerator.py, src/Execution/lbsRuntime.py, src/IO/lbsStatistics.py, src/IO/lbsVTStatisticsReader.py, src/IO/lbsVTStatisticsWriter.py, src/Model/lbsPhase.py, src/Model/lbsRank.py
=> #181: add Hamming distance with respect to optimal arrangements 

requirements.txt
- changes NumPy version to the last working version
close #185
=> #185: CI test is failing

src/Applications/conf.yaml, src/Applications/rank_object_enumerator.py, src/Execution/lbsCriterionBase.py, src/Execution/lbsRuntime.py, src/Execution/lbsTemperedCriterion.py, src/Model/lbsPhase.py
Fixes #168 #178
The same fix in the `TemperedWork` criterion actually resolves both issues at once.
=> #168: Fix TemperedWork criterion so it let not Maximum Work increase

src/Utils/vt_data_extractor.py
- removed duplicates given by user
Closes #196
=> #196: Improve phase extraction

src/Applications/LBAF.py, src/Applications/rank_object_enumerator.py, src/IO/lbsVTDataReader.py, src/IO/lbsVTDataWriter.py, src/Model/lbsPhase.py, tests/test_lbs_vt_statistics_reader.py
- changed names to `data` writer and reader
Closes #212
=> #212: Change name from statisticts to data in reader and writer

README.md, src/Utils/JSON_data_files_validator.py
- added standalone data validator
- support for single file or directory with files
Closes #221
=> #221: Prepare a standalone script for validating schema of JSON data files

src/lbaf/IO/lbsVTDataReader.py, tests/test_lbs_vt_data_reader.py, tests/test_lbs_vt_statistics_reader.py
- remove not used code
- create communicator dictionary for each phase
- updated merging rank communication to new dictionary with phase as a key
Closes #233
=> #233: Fixed reading data from files 

src/lbaf/Utils/data_stat_files_updater.py
- added utility for adding schema type to `old` data files
Closes #253
=> #253: nolb example no longer working

src/lbaf/Utils/vt_data_extractor.py
- fixed import and printing out in which dir app starts
- added automatically schema type if not found
- added option for not checking the schema
- added printing out info regarding prefix and suffix
- added printing out info when no files were found
- added printing out phases to extract
Closes #258
=> #258: Update vt_data_extractor.py

.github/workflows/acceptance-tests.yml, scripts/test_config/conf.yaml, scripts/test_config/step.yaml, scripts/test_stepper.py, src/lbaf/Applications/LBAF_app.py, src/lbaf/Applications/conf.yaml, src/lbaf/Execution/lbsAlgorithmBase.py, src/lbaf/IO/configurationValidator.py, src/lbaf/Model/lbsWorkModelBase.py, src/lbaf/Utils/logger.py
- added `Stepper-Test` job to acceptance-tests.yml
- added `log_to_file` entry in configuration files
- added `log_to_file` as optional in configurationValidator.py
- added passing config file to logger
- removed logger instantiation when importing files lbsAlgorithmBase.py and lbsWorkModelBase.py
- added possibility to logger to log output to the given file
- added test config for stepper test in CI
- added test_stepper.py script
- deactivated Acceptance Tests with Python 3.9(need to be activated once VTK works again)
Closes #261
=> #261: Add CI action to step.yaml dataset

src/lbaf/IO/lbsVTDataReader.py, src/lbaf/Model/lbsObject.py, tests/test_lbs_object.py
- added subphases to lbsObject.py
- added support for reading subphases from files
- added test for subphases
closes #268
=> #268: Load subphase data from input files

.github/workflows/build-and-publish-to-pypi.yml, scripts/test_config/conf.yaml, scripts/test_config/step.yaml, src/lbaf/Applications/LBAF_app.py, src/lbaf/Applications/conf.yaml, src/lbaf/Applications/step.yaml, src/lbaf/IO/configurationValidator.py, src/lbaf/IO/lbsMeshBasedVisualizer.py, src/lbaf/IO/lbsVTDataReader.py, src/lbaf/IO/lbsVTDataWriter.py
- saving output files in parallel (multiprocessing)
- made checking schema optional
closes #290
=> #290: look for ways to optimize the performance of LBAF

.github/workflows/acceptance-tests.yml, src/lbaf/Applications/LBAF_app.py
- removed default config file, raised Error when config file not given
closes #303
=> #303: Removed default configuration

src/lbaf/IO/lbsVTDataReader.py, src/lbaf/IO/lbsVTDataWriter.py, src/lbaf/Utils/vt_data_extractor.py
- set context for multiprocessing Pool
closes #310
=> #310: SchemaValidator execution error in develop branch

src/lbaf/IO/lbsVTDataReader.py
Cf. my detailed explanations about what was incorrect in the execution logic of that code, in the comments section of #312
=> #312: phases that are not of interest must be ignored altogether

src/lbaf/Applications/LBAF_app.py, src/lbaf/IO/lbsStatistics.py
=> #317: Reformat style of lbsStatistics, remove special handling of text string for imbalance file

src/lbaf/Applications/LBAF_app.py, src/lbaf/Applications/conf.yaml, src/lbaf/Execution/lbsAlgorithmBase.py, src/lbaf/Execution/lbsBruteForceAlgorithm.py, src/lbaf/Execution/lbsInformAndTransferAlgorithm.py, src/lbaf/Execution/lbsPhaseStepperAlgorithm.py, src/lbaf/IO/lbsMeshBasedVisualizer.py, src/lbaf/IO/lbsStatistics.py, src/lbaf/Model/lbsObjectCommunicator.py, src/lbaf/Model/lbsPhase.py, src/lbaf/Utils/logger.py, tests/test_lbs_phase.py
Resolves #322
Fixes #328 
NB: the latter was discovered while working on the former
=> #322: Refactoring to remove edge cache; create edge updater; and fix issue discovered in inter-object visualization

scripts/test_stepper.py, src/lbaf/Applications/LBAF_app.py, src/lbaf/Applications/conf.yaml, src/lbaf/Execution/lbsAlgorithmBase.py, src/lbaf/Execution/lbsBruteForceAlgorithm.py, src/lbaf/Execution/lbsInformAndTransferAlgorithm.py, src/lbaf/Execution/lbsRuntime.py, src/lbaf/Execution/lbsStrictLocalizingCriterion.py, src/lbaf/Execution/lbsTemperedCriterion.py, src/lbaf/IO/configurationValidator.py, src/lbaf/IO/lbsMeshBasedVisualizer.py, src/lbaf/IO/lbsStatistics.py, src/lbaf/Model/lbsLoadOnlyWorkModel.py, src/lbaf/Model/lbsObject.py, src/lbaf/Model/lbsPhase.py, src/lbaf/Model/lbsRank.py, src/lbaf/Model/lbsWorkModelBase.py
=> #231: statistics and algorithms overhaul

.github/workflows/acceptance-tests.yml, .github/workflows/action-git-diff-check.yml, .github/workflows/check-commit-format.yml, .github/workflows/check-pr-fixes-issue.yml, .github/workflows/find-trailing-whitespace.yml, .github/workflows/find-unsigned-commits.yml, .github/workflows/unit-tests.yml, README.md, src/lbaf/IO/lbsMeshBasedVisualizer.py
=> #220: copy workflows from the template-repository

src/lbaf/Applications/LBAF_app.py, src/lbaf/IO/lbsVisualizer.py
=> #322: show ending iteration and I in visualization

src/lbaf/Applications/LBAF_app.py, src/lbaf/Applications/exotest.py, src/lbaf/Execution/lbsAlgorithmBase.py, src/lbaf/Execution/lbsRuntime.py, src/lbaf/IO/lbsStatistics.py, src/lbaf/IO/lbsVisualizer.py, src/lbaf/Model/lbsRank.py
Fixes #175 
Also make additional minor improvements to LBAF_Viz
=> #175: diagnose bug in VTK > 9.0.1 Python wheel re: ExodusII writer

src/lbaf/Execution/lbsClusteringTransferStrategy.py
Resolves #364 
Also made some code style improvement to the clustering algorithm code in passing
=> #364: resolve division by 0 error when no migratable clusters exist 

tests/test_schema_validator.py
=> #372: fix relative import path

README.md
=> #393: Verify/Update the online documentation

src/lbaf/IO/lbsVisualizer.py
=> #370: make categorical labels integers

src/lbaf/Execution/lbsCentralizedPrefixOptimizerAlgorithm.py
=> #415:  Fix ModuleNotFoundError: No module named 'lbaf.Utils.exception_handler' #415 

config/conf.yaml, src/lbaf/Execution/lbsAlgorithmBase.py, src/lbaf/Execution/lbsCentralizedPrefixOptimizerAlgorithm.py, src/lbaf/Execution/lbsClusteringTransferStrategy.py, src/lbaf/Execution/lbsRecursiveTransferStrategy.py, src/lbaf/Execution/lbsTransferStrategyBase.py, src/lbaf/Model/lbsPhase.py
Resolves #414 
Also improved the code as a result of the review of the control flow, by factoring out commonalities between the 2 transfer strategies and moving them to the abstract base strategy.
Resolves #375 as well, as discovered by @cwschilly
=> #414 modify traversal of ranks to better emulate asynchrony

src/lbaf/Applications/LBAF_app.py, src/lbaf/Applications/MoveCountsViewer.py, src/lbaf/Utils/lbsCsv2JsonDataConverter.py, src/lbaf/Utils/lbsDataStatFilesUpdater.py, src/lbaf/Utils/lbsJSONDataFilesValidatorLoader.py, src/lbaf/Utils/lbsVTDataExtractor.py, src/lbaf/Utils/lbsWeb.py, src/lbaf/__init__.py, src/lbaf/__main__.py
=> #376: fix running a script from the script parent folder

README.md, src/lbaf/Applications/LBAF_app.py
=> #429: Move printed QOI to beginning of LBAF output

config/challenging-toy-fewer-tasks.yaml, config/user-defined-memory-toy-problem.yaml, src/lbaf/Execution/lbsClusteringTransferStrategy.py
=> #428: allow swaps of empty clusters from target

README.md
=> #424: Create README for release

.github/workflows/build-and-publish-to-pypi.yml, README.md, setup.cfg, src/lbaf/__init__.py
=> #442: Prepare for release

README.md
=> #449: Fix readme link

config/user-defined-memory-toy-problem.yaml, src/lbaf/IO/lbsVTDataWriter.py, src/lbaf/Model/lbsObject.py
=> #421: make lbsVTDataWriter at parity with the lbsVTDataReader for user-defined data

src/lbaf/Execution/lbsInformAndTransferAlgorithm.py
=> #439: Add timers for LBs per iteration

src/lbaf/Applications/LBAF_app.py, src/lbaf/Execution/lbsInformAndTransferAlgorithm.py
=> #441: Run new performance profiler to see if there are places we can improve it

src/lbaf/__init__.py
=> #457: Create 1.0.1 micro revision

config/challenging-toy-fewer-tasks.yaml, data/user-defined-memory-toy-problem/toy_mem.0.json, src/lbaf/Execution/lbsAlgorithmBase.py, src/lbaf/Execution/lbsClusteringTransferStrategy.py, src/lbaf/Execution/lbsInformAndTransferAlgorithm.py, src/lbaf/Execution/lbsRuntime.py, src/lbaf/Execution/lbsTransferStrategyBase.py, src/lbaf/IO/lbsStatistics.py
Resolves #446 
Related (and sequel to) #464 and PR #465
=> #446: Resolve performance issue with subclustering improvements 

src/lbaf/Applications/LBAF_app.py
=> #474: Print the statistics of number and ratio of uprooted blocks at the end

src/lbaf/Execution/lbsAlgorithmBase.py, src/lbaf/Execution/lbsClusteringTransferStrategy.py, src/lbaf/Execution/lbsTransferStrategyBase.py, src/lbaf/IO/lbsConfigurationValidator.py, tests/unit/Execution/test_lbs_clustering_transfer_strategy.py, tests/unit/IO/test_configuration_validator.py, tests/unit/config/conf_correct_clustering.yml, tests/unit/config/conf_wrong_separate_subclustering.yml
=> #486: Implement a way to optionally start subclustering after all ranks have stopped swapping

data/user-defined-memory-toy-problem/toy_mem_README.0.json, data/user-defined-memory-toy-problem/toy_mem_README.1.json, data/user-defined-memory-toy-problem/toy_mem_README.2.json, data/user-defined-memory-toy-problem/toy_mem_README.3.json, data/user-defined-memory-toy-problem/toy_mem_optimal.0.json, data/user-defined-memory-toy-problem/toy_mem_optimal.1.json, data/user-defined-memory-toy-problem/toy_mem_optimal.2.json, data/user-defined-memory-toy-problem/toy_mem_optimal.3.json
=> #491: Added data files corresponding to README and optimal arrangements

src/lbaf/IO/lbsVTDataReader.py
=> #493: Runtime error with new VT reader for user defined toy problem

config/test-vt-tv.yaml
=> #510: Change configuration to use relative path for input data

src/lbaf/Applications/LBAF_app.py, tests/unit/IO/test_lbs_visualizer_deprecation.py
=> #512:  LBAF should report an error or a warning when vt-tv is not found but is requested

src/lbaf/Applications/MoveCountsViewer.py
=> #513:  Different runtime errors occurring depending on whether vtk package is installed or not

.github/workflows/code-quality.yml, .pylintrc, docs/pages/dependencies.rst, requirements.txt, setup.cfg, src/lbaf/Execution/lbsClusteringTransferStrategy.py, src/lbaf/Execution/lbsTransferStrategyBase.py, src/lbaf/IO/lbsVTDataReader.py, src/lbaf/IO/lbsVTDataWriter.py, src/lbaf/IO/lbsVisualizer.py, src/lbaf/Model/lbsPhase.py, src/lbaf/__init__.py, tests/unit/IO/test_configuration_validator.py, tox.ini
Fixes #509
This PR expands support for Python 3.10 and 3.11.
It also updates all package dependencies to the most recent supported versions. 
Related to [PR 72](https://github.com/DARMA-tasking/vt-tv/pull/72) in vt-tv
=> #509:  Investigate compatibility with more recent versions of Python than 3.9

config/permute.yaml, src/lbaf/Applications/LBAF_app.py, src/lbaf/Execution/lbsAlgorithmBase.py, src/lbaf/Execution/lbsPrescribedPermutationAlgorithm.py, src/lbaf/IO/lbsConfigurationValidator.py, src/lbaf/Model/lbsPhase.py
=> #544: Add a new algorithm to implement the permutations prescribed by CCM-MILP

.github/workflows/deploy_docs.yml, docs/docs_config.py, requirements.txt, setup.cfg
=> #539: Fix documentation deployment pipeline

src/lbaf/Execution/lbsClusteringTransferStrategy.py, src/lbaf/Execution/lbsInformAndTransferAlgorithm.py, src/lbaf/Execution/lbsRecursiveTransferStrategy.py, src/lbaf/Execution/lbsTransferStrategyBase.py, src/lbaf/IO/lbsConfigurationValidator.py, tests/unit/Execution/test_lbs_clustering_transfer_strategy.py, tests/unit/IO/test_configuration_validator.py, tests/unit/config/conf_correct_subclustering_filters.yml, tests/unit/config/conf_wrong_subclustering_minimum_improvement.yml, tests/unit/config/conf_wrong_subclustering_threshold.yml
=> #487: Introduce additional filters prior to subclustering

.github/workflows/deploy_docs.yml, docs/docs_config.py, docs/pages/configuration.rst, docs/pages/getting_started.rst
=> #553: Fix "Getting Started" page of documentation

tests/acceptance/test_permutations.py, tests/acceptance/test_synthetic_blocks.py
Fixes #533 
This PR adds testing for the following cases:
| alpha  | beta |  | W_max     |
| --------- | ------ |--| -------------- |
| 1.0       | 0.0   |  | 2.0 or 2.5  |
| 0.0       | 1.0   |  | 0.0              |
| 1.0       | 1.0   |  | 4.0  or 4.5  |
=> #533: Add test cases for communication alone and mixed compute-communication case

src/lbaf/IO/lbsVTDataReader.py, src/lbaf/IO/lbsVTDataWriter.py, src/lbaf/Model/lbsObject.py
=> #560: object: add index from json if it exists to object

config/ccm-example.yaml, config/conf.yaml, config/permute.yaml, config/synthetic-blocks.yaml, config/test-vt-tv.yaml, config/user-defined-memory-toy-problem.yaml, src/lbaf/Applications/LBAF_app.py, src/lbaf/Execution/lbsAlgorithmBase.py, src/lbaf/Execution/lbsCriterionBase.py, src/lbaf/Execution/lbsInformAndTransferAlgorithm.py, src/lbaf/Execution/lbsRuntime.py, src/lbaf/IO/lbsConfigurationValidator.py, src/lbaf/IO/lbsVTDataReader.py, src/lbaf/IO/lbsVTDataWriter.py, src/lbaf/Model/lbsObject.py, src/lbaf/Model/lbsPhase.py, src/lbaf/Model/lbsRank.py, tests/unit/Applications/test_lbaf_app.py, tests/unit/Execution/test_lbs_brute_force_algorithm.py, tests/unit/Execution/test_lbs_centralized_prefix_optimizer_algorithm.py, tests/unit/Execution/test_lbs_clustering_transfer_strategy.py, tests/unit/Execution/test_lbs_inform_and_transfer_algorithm.py, tests/unit/Execution/test_lbs_recursive_transfer_strategy.py, tests/unit/Execution/test_lbs_transfer_strategy_base.py, tests/unit/IO/test_lbs_vt_data_reader.py, tests/unit/Model/test_lbs_rank.py, tests/unit/Model/test_lbs_work_models.py, tests/unit/config/conf_vt_writer_communications_test.yaml, tests/unit/config/conf_vt_writer_stepper_test.yml, tests/unit/config/user-defined-memory-toy-problem.yaml
=> #566: complete lb iterations support

src/lbaf/IO/lbsVTDataWriter.py, src/lbaf/Model/lbsRank.py
=> #575: qois: fix rank qois

src/lbaf/IO/lbsVTDataWriter.py
=> #578: Fix homed ratio in LB iter due to bad indent

setup.cfg, src/lbaf/Utils/lbsJSONTaskLister.py, src/lbaf/__init__.py
=> #582: Add JSON task lister utility script

tests/acceptance/config/synthetic-acceptance.yaml
=> #586: Investigate erratic and unpredictable CI error regarding synthetic case

config/challenging-toy-hundreds-tasks.yaml, src/lbaf/Execution/lbsClusteringTransferStrategy.py
=> #601: Fix bug in output console

src/lbaf/Execution/lbsClusteringTransferStrategy.py
=> #603: Fix incorrect handling of no-subcluster mode
